#!/bin/sh

# Script para compilar todo o projeto (32 e 64 bits)
# Autor: Lucas Vieira de Jesus

# Pré-definições
RED='\x1b[1;31m'
GREEN='\x1b[1;32m'
YELLOW='\x1b[1;33m'
BLUE='\x1b[1;34m'
MAGENTA='\x1b[1;35m'
CYAN='\x1b[1;36m'
RESET='\x1b[0m'

# Subrotinas
function log_alerta()
{
	echo -e "${YELLOW}[!]${RESET} $1"
}

function log_err()
{
	echo -e "${RED}[!]${RESET} $1"
}

function log_info()
{
	echo -e "${BLUE}[*]${RESET} $1"
}

function log_ok()
{
	echo -e "${GREEN}[+]${RESET} $1"
}

function log_pergunta()
{
	echo -e "${YELLOW}[?]${RESET} $1"
}

function log_show()
{
	echo -e "${RED}[*]${RESET} $1"
}

log_info "Compilando o projeto ...\n"

if [ "$1" == "64" ]; then
	make -f Makefile_x64.mak > /dev/null
	if [ "$?" != "0" ]; then
		log_err "Falha ao compilar projeto 64 bits"
	else
		log_ok "Projeto 64 bits compilado com sucesso"
	fi
elif [ "$1" == "32" ]; then
	make -f Makefile_x86.mak > /dev/null
	if [ "$?" != "0" ]; then
		log_err "Falha ao compilar projeto 32 bits"
	else
		log_ok "Projeto compilado com sucesso\n"
	fi
else
	log_err "Opção inválida\n"
fi




